# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5a94d9efd6d7666d264e5201f7aac2190cbe52ab9de5bba8eb42121e96952ca9193963f840ea9e74dd4e4b43325e1d23641a3e5e415c0d1584b149b9d1f1016

test:
  secret_key_base: b846ed8a95407c1cfc89fa990ff2fde03089501cc6c1dddae5d083de99e66d847d0cbcac21f03f997287d1c749751b40b20ea74ef865c54b9e71a2f6a418d33e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
